Feature/add compatibility for lmrfy
ZigmundKreud/cof pull request #86
Opened 2021-08-23 20:16 UTC by Quelu

Ajout d'une nouvelle méthode `rollAbility` sur la classe `Actor` et de la configuration dans l'objet `CONFIG` pour reprendre les conventions des autres systèmes de jeu.
Cette modification permet de faire fonctionner le module [Let Me Roll That For You!](https://github.com/League-of-Foundry-Developers/fvtt-module-lmrtfy) pour lequel je vais également faire une PR.

2021-09-09 23:40 UTC, Eryan9 commented
Malheureusement le module "Let Me Roll That For You!" nous oblige à faire des PR dans leur module pour pouvoir fonctionner avec notre système.
Lors de modification dans la structure de notre fichier de configuration ou d'un renommage de méthode, il nous faudrait de nouveau faire des PR dans leur module.
Nous ne souhaitons pas lier le système CO de cette manière à un module externe et créer de dépendance.

En conséquence, nous ne développerons pas la compatibilité avec ce module.

2021-09-10 07:48 UTC, Quelu commented
C'est le principe d'un module de s'adapter au système et non l'inverse non ?
J'ai fait une [PR](https://github.com/League-of-Foundry-Developers/fvtt-module-lmrtfy/pull/114) dans le module qui a été acceptée pour y ajouter la compatibilité pour le système COF. Ils ont justement mis en place une structure permettant facilement d'ajouter des systèmes en plus (car c'est le principe de Foundry d'être "system agnostic").

Les modifications que j'ai réalisée ici ne sont que des mises en place de conventions utilisées par les autres systèmes Foundry (D&D5, PF2, ...). Ces conventions sont utilisées par tous les plugins Foundry et permettent d'ajouter et de maintenir facilement des modules.

2021-09-10 10:40 UTC, Eryan9 commented
C'est bien au module de s'adapter, j'ai marqué une connerie au dessus
En première lecture, j'avais pris les modifs comme une adaptation du système pour spécifiquement le module lmrfy.
Alors qu'en faite il ne s'agit que d'exposer des éléments du systèmes pour tous les modules.
Une nouvelle PR sera faite pour exposer les paramètres nécessaire

2021-09-10 10:46 UTC, Quelu commented
Ok pas de problèmes mais pourquoi ne pas prendre cette PR qui fait déjà l'adaptation des paramètres nécessaire ?

2021-09-10 10:56 UTC, Eryan9 commented
Parce que l'on as une autre issue pour ajouter la compatibilité avec Token Action HUD et que je pensais faire les 2 en même temps vu qu'on va pas release dans les jours à venir
Mais bon c'est pareil
Par contre, s'il te plaît retire tous les modifications qui ne sont que des modifs de "whitespace" et qui n'ont rien à voir avec le sujet avec l'on merge la PR

2021-09-10 11:11 UTC, Quelu commented
Ok c'est fait, il pourrait être bon de faire une PR pour nettoyer les espaces inutiles et de reformater le code avec un _Prettier_ ou _editorConfig_ pour que tous les contributeurs aient le même code style.

2021-09-10 19:30 UTC, Eryan9 requested changes
Remplacement du terme "Ability" par "Stat' pour la cohérence avec le reste du système

2021-09-10 19:30 UTC, Eryan9 commented on module/actors/actor.js
> +    rollAbility(ability, options = {}) {
Remplacer :
rollAbility(ability, options = {}) {
par :
rollStat(stat, options = {}) {

2021-09-10 19:30 UTC, Eryan9 commented on module/actors/actor.js
> +        return Macros.rollStatMacro(this, ability, bonus, malus);
Remplacer :
ability 
par : 
stat

2021-09-10 19:30 UTC, Eryan9 commented on module/system/config.js
> +COF.abilities = {
Remplacer :
COF.abilities
par :
COF.stats

2021-09-10 19:30 UTC, Eryan9 commented on module/system/config.js
> +COF.abilityAbbreviations = {
Remplacer :
COF.abilityAbbreviations
par :
COF.statAbbreviations

2021-09-11 13:30 UTC, Eryan9 commented
Peux-tu s'il te plait faire les renommages demandés ?
Une fois que ce sera fait nous pourrons merge la PR, la review est faite

2021-09-16 17:04 UTC, Quelu commented
C'est fait :)

2021-09-19 21:43 UTC, merged